# Generated by Django 2.1.7 on 2019-04-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marca', models.CharField(max_length=200)),
                ('Referencia', models.CharField(max_length=200)),
                ('Matricula', models.CharField(max_length=200)),
                ('Ano_Fabrico', models.IntegerField(max_length=20)),
                ('Distancia_Percorrida', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=200)),
                ('Apelido', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('Morada', models.CharField(max_length=200)),
                ('Telefone', models.IntegerField(max_length=9)),
            ],
        ),
    ]
