# Generated by Django 2.1.7 on 2019-04-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carro',
            old_name='Ano_Fabrico',
            new_name='ano_fabrico',
        ),
        migrations.RenameField(
            model_name='carro',
            old_name='Distancia_Percorrida',
            new_name='distancia_percorrida',
        ),
        migrations.RenameField(
            model_name='carro',
            old_name='Marca',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='carro',
            old_name='Matricula',
            new_name='matricula',
        ),
        migrations.RenameField(
            model_name='carro',
            old_name='Referencia',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='utilizador',
            old_name='Apelido',
            new_name='apelido',
        ),
        migrations.RenameField(
            model_name='utilizador',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='utilizador',
            old_name='Morada',
            new_name='morada',
        ),
        migrations.RenameField(
            model_name='utilizador',
            old_name='Nome',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='utilizador',
            old_name='Telefone',
            new_name='telefone',
        ),
        migrations.AddField(
            model_name='carro',
            name='preco',
            field=models.IntegerField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
