# Generated by Django 2.1.7 on 2019-04-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_auto_20190415_1536'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Utilizador',
            new_name='Cliente',
        ),
        migrations.AddField(
            model_name='carro',
            name='imagem',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
