# Generated by Django 2.1.7 on 2019-05-16 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_auto_20190516_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resposta',
            old_name='resposta',
            new_name='texto',
        ),
    ]
